# Generated by Django 4.0.4 on 2022-05-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_list', models.CharField(blank=True, max_length=50, null=True)),
                ('password_list', models.CharField(blank=True, max_length=50, null=True)),
                ('email_list', models.EmailField(blank=True, max_length=50, null=True)),
                ('name_list', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_list', models.IntegerField(blank=True, max_length=50, null=True)),
                ('gender_list', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday_list', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dreamreal',
            },
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('img', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.EmailField(blank=True, max_length=500, null=True)),
                ('money', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Web',
            },
        ),
    ]
